package dto

import (
	"time"

	"github.com/imperiuse/golib/db"
)

// Various example of DTO's
type (
	NotDTO struct{}

	BaseDTO struct {
		ID        db.ID     `db:"id"          orm_use_in:"select"`
		CreatedAt time.Time `db:"created_at"  orm_use_in:"select"`
		UpdatedAt time.Time `db:"updated_at"  orm_use_in:"select,update"`
	}

	User struct {
		BaseDTO
		Name     string `db:"name"     orm_use_in:"select,create,update"`
		Email    string `db:"email"    orm_use_in:"select,create,update"`
		Password string `db:"password" orm_use_in:"select,create,update"`
		RoleID   db.ID  `db:"role_id" orm_use_in:"select,create,update"`
		_        any    `orm_table_name:"Users" orm_alias:"u"`
	}

	Role struct {
		BaseDTO
		Name   string `db:"name"       orm_use_in:"select,create,update"`
		Rights int    `db:"rights"     orm_use_in:"select,create,update"`
		_      any    `orm_table_name:"Roles" orm_alias:"r"`
	}

	UsersRole struct {
		User `db:"u" orm_alias:"u"`
		Role `db:"r" orm_alias:"r"`
		_    any `orm_join:" ON u.role_id = r.id "`
	}

	Paginator struct {
		BaseDTO
		Name string `db:"name"       orm_use_in:"select,create,update"`

		_ any `orm_table_name:"Paginators"`
	}
)

func (b BaseDTO) Identity() db.ID {
	return b.ID
}

func (_ Paginator) Repo() db.Table {
	return "Paginators"
}

func (_ Role) Repo() db.Table {
	return "Roles"
}

func (_ User) Repo() db.Table {
	return "Users"
}

var DSL = map[string]string{
	"Roles": `CREATE TABLE IF NOT EXISTS Roles
(
id           INTEGER     PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
created_at   TIMESTAMP   NOT NULL DEFAULT NOW(),
updated_at   TIMESTAMP   NOT NULL DEFAULT NOW(),
name         TEXT        NOT NULL,
rights      INTEGER     NOT NULL
);`,
	"Users": `CREATE TABLE IF NOT EXISTS Users
(
id           INTEGER     PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
created_at   TIMESTAMP   NOT NULL DEFAULT NOW(),
updated_at   TIMESTAMP   NOT NULL DEFAULT NOW(),
name         TEXT        NOT NULL,
email        TEXT        NOT NULL,
password     TEXT        NOT NULL,
role_id      INTEGER     NOT NULL,
CONSTRAINT fkey__r FOREIGN KEY (role_id) REFERENCES roles (id) MATCH SIMPLE	ON UPDATE NO ACTION ON DELETE CASCADE
);`,
	"Paginators": `CREATE TABLE IF NOT EXISTS Paginators
(
id           INTEGER     PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
created_at   TIMESTAMP   NOT NULL DEFAULT NOW(),
updated_at   TIMESTAMP   NOT NULL DEFAULT NOW(),
name         TEXT        NOT NULL
);`,
}
